apiVersion: v1
kind: Secret
metadata:
  name: jiaa-ai-secret
type: Opaque
data:
  openai_api_key: MUJscFQzQmxia0ZKbC1iTFBGaDJFUEUwNmJRZENJNUdPX3M0R3BZRTFLM0VveW05a09Jb0VhV0tBdlpuMWJPZGtta19qSmM2VGZjcl9LNzlDRmhFNEE=
---
apiVersion: v1
kind: Secret
metadata:
  name: jiaa-db-secret
type: Opaque
data:
  pg_user: amlhYV9hZG1pbg==  # jiaa_admin
  pg_password: amlhYTEyMzQhIQ== # jiaa1234!!
---
apiVersion: v1
kind: Secret
metadata:
  name: jiaa-influx-secret
type: Opaque
data:
  # Placeholder: Replace with actual InfluxDB token using base64 encoding
  token: Q0hBTkdFX01FX0lORkxVX1RPS0VO # CHANGE_ME_INFLUX_TOKEN
